PBM-539 Updated install/upgrade docs with installing fro pbm repo
percona/percona-backup-mongodb pull request #410
Opened 2020-09-03 11:33 UTC by nastena1606

2020-09-03 12:11 UTC, EvgeniyPatlan requested changes

2020-09-03 12:11 UTC, EvgeniyPatlan commented on doc/source/installation.rst
> +the |percona-release| utility. Starting from v1.2.1, |pbm| packages are stored in the *pbm* repository.
```suggestion
the |percona-release| utility. Starting from v1.3.0, |pbm| packages are stored in the *pbm* repository.
```

2020-09-03 12:26 UTC, EvgeniyPatlan approved these changes

2020-09-03 12:26 UTC, EvgeniyPatlan commented on doc/source/upgrading.rst
> +2. Starting from version 1.2.1, |pbm| packages are stored in the *pbm* repository and the *tools* repository for backward compatibility. To upgrade to the version lower than 1.2.1, enable the *tools*
```suggestion
2. Starting from version 1.3.0, |pbm| packages are stored in the *pbm* repository and the *tools* repository for backward compatibility. To upgrade to the version lower than 1.3.0, enable the *tools* repository.
```

2020-09-03 12:26 UTC, EvgeniyPatlan requested changes
1.3.0

2020-09-03 12:51 UTC, EvgeniyPatlan approved these changes

2020-09-14 05:50 UTC, akira-kurogane approved these changes
LGTM

2020-09-14 06:09 UTC, merged