PBM-551 fix: unify log timezones and date/time format
percona/percona-backup-mongodb pull request #416
Opened 2020-09-18 12:21 UTC by dAdAbird

Timezone across the log unified to the **_local format_** (not UTC) as there is no way to change that option for the mongo-tools (mongodump/mongorestre) logger.

Also mongo-tools data/time format chawed to be consistent with the rest of the logs.

For example

was
```
2020/09/18 15:12:55 [INFO] backup/2020-09-18T12:12:38Z: backup started
2020-09-18T15:12:58.0001+0300	writing admin.system.users to archive on stdout
2020-09-18T15:12:58.0001+0300	done dumping admin.system.users (2 documents)
2020-09-18T15:12:58.0001+0300	done dumping config.migrations (0 documents)
2020/09/18 15:12:58 [INFO] backup/2020-09-18T12:12:38Z: mongodump finished, waiting for the oplog
```

now
```
2020/09/18 15:12:55 [INFO] backup/2020-09-18T12:12:38Z: backup started
2020/09/18 15:12:58 writing admin.system.users to archive on stdout
2020/09/18 15:12:58 done dumping admin.system.users (2 documents)
2020/09/18 15:12:58 done dumping config.migrations (0 documents)
2020/09/18 15:12:58 [INFO] backup/2020-09-18T12:12:38Z: mongodump finished, waiting for the oplog
```

2020-09-18 12:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

2020-09-23 09:38 UTC, akira-kurogane requested changes

2020-09-23 09:38 UTC, akira-kurogane commented on pbm/log.go
> +const LogTimeFormat = "2006/01/02 15:04:05"
Can we use ISO-8601 instead please?
i.e. "2006-01-02T15:04:05"
Or rather "2006-01-02T15:04:05Z" to indicate UTC timezone.

2020-09-23 14:36 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

2020-09-23 14:37 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.2 | failed |
| mongodb 4.0 | failed |

2020-09-24 01:07 UTC, akira-kurogane approved these changes
Thanks Andrew.

2020-09-24 09:23 UTC, merged