Pbm 435 doc pbm status
percona/percona-backup-mongodb pull request #478
Opened 2020-12-17 13:01 UTC by nastena1606

2020-12-21 08:10 UTC, akira-kurogane requested changes
Hi Anastasia.

"pbm list" will from 1.4 only list completed backups, so the "Checking an in-progress backup" section of running.rst should no longer advise that you might see an "In progress" label.

2020-12-21 08:10 UTC, akira-kurogane commented on doc/source/running.rst
> +'In progress' label. When that is absent, the backup is complete.
This is no longer the case I thought.

2020-12-21 08:10 UTC, akira-kurogane commented on doc/source/status.rst
> +- Running backups / restores, if any
```suggestion
- The currently running backups / restores, if any
```

2020-12-22 05:14 UTC, akira-kurogane approved these changes
Hi @nastena1606. Thanks for change.

2020-12-22 13:58 UTC, sandraromanchenko approved these changes

2020-12-22 19:29 UTC, dAdAbird approved these changes

2020-12-24 15:24 UTC, merged