PBM-661: CI tests
percona/percona-backup-mongodb pull request #524
Opened 2021-04-01 16:37 UTC by dAdAbird

2021-04-01 16:45 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

2021-04-02 07:24 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

2021-04-02 09:34 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | passed |
| mongodb 4.0 | passed |
| mongodb 4.2 | failed |

2021-04-02 18:31 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

2021-04-02 19:19 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| mongodb 3.6 | failed |
| mongodb 4.0 | failed |
| mongodb 4.2 | failed |

2021-04-05 18:24 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.0 | failed |
| Restore on new cluster mongodb 4.2 | failed |
| Sharded cluster mongodb 3.6 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |

2021-04-05 19:28 UTC, hors requested changes

2021-04-05 19:28 UTC, hors commented on Jenkinsfile
> +    sh '''
```suggestion
    sh """
```

2021-04-05 19:28 UTC, hors commented on Jenkinsfile
> +    '''
```suggestion
    """
```

2021-04-05 19:28 UTC, hors commented on Jenkinsfile
> +        sh '''
```suggestion
        sh """
```

2021-04-05 19:28 UTC, hors commented on Jenkinsfile
> +        '''
```suggestion
        """
```

2021-04-06 17:35 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.0 | failed |
| Restore on new cluster mongodb 4.2 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Sharded cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |

2021-04-08 10:57 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.0 | failed |
| Restore on new cluster mongodb 4.2 | failed |
| Sharded cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | passed |

2021-04-08 12:57 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | failed |

2021-04-08 14:29 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |

2021-04-08 17:21 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |

2021-04-08 19:26 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 3.6 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | passed |

2021-04-09 09:04 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 3.6 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 3.6 | failed |
| Sharded cluster mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |

2021-04-09 09:54 UTC, akira-kurogane approved these changes
LGTM. Thanks for the CI testing TLC.

2021-04-09 16:13 UTC, hors approved these changes

2021-04-09 17:02 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Restore on new cluster mongodb 3.6 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 3.6 | failed |
| Non-sharded replicaset mongodb 3.6 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |

2021-04-09 17:25 UTC, merged