PBM-674 Added a FAQ section
percona/percona-backup-mongodb pull request #560
Opened 2021-07-02 06:15 UTC by nastena1606

2021-07-12 00:16 UTC, akira-kurogane requested changes

2021-07-12 00:16 UTC, akira-kurogane commented on doc/source/faq.rst
> +``pbm-agents`` use UTC time zone by design. The reason behind this is to avoid user misunderstandings when replica set / cluster nodes are distributed geographically in different time zones.
:+1:

2021-07-12 00:16 UTC, akira-kurogane commented on doc/source/faq.rst
> +PBM takes a backs up the whole state of a sharded cluster and this guarantees data consistency during the restore.
:+1:

2021-07-12 00:16 UTC, akira-kurogane commented on doc/source/faq.rst
> +If you are not using a sharded cluster, or the sharded cluster is only 2 or 3 shards, we recommend using ``-d`` and ``-c`` options with ``mongodump`` and/or ``mongorestore``. As ``mongodump``/``mongo
```suggestion
If single-collection restores are your primary requirement and you are not using a sharded cluster, or the sharded cluster is only 2 or 3 shards, we recommend using ``-d`` and ``-c`` options with ``mongodump`` and/or ``mongorestore``. As ``mongodump``/``mongorestore`` connects directly to the primary (in a non-sharded replica set) or via a ``mongos`` node in a cluster, it sees the cluster as if it were a single node, making it simple. ``mongodump``/``mongorestore`` work in a single process, so if you aren’t reinserting to many shards, the lack of parallelization won't be too bad.
```

2021-07-12 12:30 UTC, akira-kurogane approved these changes
Thanks Anastasia!

2021-08-11 11:09 UTC, dAdAbird approved these changes

2021-08-16 14:32 UTC, merged