PBM-734: add storage.s3.debugLogLevels option
percona/percona-backup-mongodb pull request #625
Opened 2021-12-30 11:33 UTC by defbin

2021-12-30 14:39 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 4.4 | passed |
| Sharded cluster mongodb 5.0 | failed |
| Non-sharded replicaset mongodb 4.4 | passed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.4 | passed |
| Restore on new cluster mongodb 4.4 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.0 | passed |
| Restore on new cluster mongodb 5.0 | passed |
| Single-node replicaset mongodb 5.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 5.0 | passed |

2021-12-30 16:06 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |

2021-12-30 17:05 UTC, dAdAbird requested changes

2021-12-30 17:05 UTC, dAdAbird commented on pbm/storage/s3/s3.go
> +			fmt.Fprintf(out, "WARN: S3 client debug log level: duplicated %q\n", lvl)
s/WARN/Warning
In other places in CLI we are using the`"Error:.."` format. `"Warning: ..."` would be more consistent

2021-12-30 17:59 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 4.2 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Sharded cluster mongodb 4.4 | failed |
| Sharded cluster mongodb 5.0 | failed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Restore on new cluster mongodb 5.0 | passed |
| Non-sharded replicaset mongodb 4.4 | passed |
| Non-sharded replicaset mongodb 5.0 | passed |
| Single-node replicaset mongodb 4.4 | failed |
| Restore on new cluster mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Single-node replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 5.0 | failed |
| Single-node replicaset mongodb 4.2 | failed |
| Restore on new cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 4.4 | passed |

2021-12-30 19:09 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Single-node replicaset mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.4 | passed |
| Single-node replicaset mongodb 4.0 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.4 | failed |
| Non-sharded replicaset mongodb 5.0 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Single-node replicaset mongodb 5.0 | failed |
| Restore on new cluster mongodb 5.0 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 4.4 | passed |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 5.0 | failed |
| Sharded cluster mongodb 4.4 | passed |

2021-12-30 20:00 UTC, defbin commented on pbm/storage/s3/s3.go
> +	for _, lvl := range strings.Split(levels, ",") {
I understand it. My point was to inform users if they made a mistake. IMO any feedback from a tool is good UX and part of the interface. For me, warning let me know something could work not I expect or ask, e.g., modified after applying like with `" HTTPBody " => "HTTPBody"`. BTW the original passed value is stored in config without corrections.

Anyway, I'll remove the warnings and only leave about an unsupported level type.

2021-12-30 20:13 UTC, defbin commented on pbm/config.go
> +		s3.SDKLogLevel(cfg.Storage.S3.DebugLogLevels, os.Stderr)
I didn't get why we need the comment?  `s3.SDKLogLevel()` has a doc comment that describes how it could use the `os.Stderr`.

2021-12-30 23:07 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 4.4 | failed |
| Sharded cluster mongodb 4.2 | passed |
| Sharded cluster mongodb 5.0 | failed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Non-sharded replicaset mongodb 4.0 | passed |
| Restore on new cluster mongodb 4.4 | passed |
| Non-sharded replicaset mongodb 4.4 | passed |
| Restore on new cluster mongodb 5.0 | passed |
| Non-sharded replicaset mongodb 5.0 | failed |
| Single-node replicaset mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.4 | passed |
| Single-node replicaset mongodb 4.2 | passed |
| Single-node replicaset mongodb 5.0 | failed |

2022-01-13 08:09 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 4.2 | failed |
| Sharded cluster mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 4.4 | failed |
| Restore on new cluster mongodb 4.4 | passed |
| Non-sharded replicaset mongodb 4.2 | failed |
| Restore on new cluster mongodb 5.0 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Restore on new cluster mongodb 4.0 | passed |

2022-01-13 10:58 UTC, JNKPercona commented
| Test name  | Status |
| ------------- | ------------- |
| Sharded cluster mongodb 4.0 | passed |
| Sharded cluster mongodb 5.0 | passed |
| Sharded cluster mongodb 4.4 | passed |
| Sharded cluster mongodb 4.2 | passed |
| Non-sharded replicaset mongodb 4.0 | failed |
| Non-sharded replicaset mongodb 5.0 | passed |
| Non-sharded replicaset mongodb 4.4 | passed |
| Single-node replicaset mongodb 5.0 | passed |
| Single-node replicaset mongodb 4.2 | passed |
| Restore on new cluster mongodb 5.0 | passed |
| Non-sharded replicaset mongodb 4.2 | passed |
| Restore on new cluster mongodb 4.4 | passed |
| Restore on new cluster mongodb 4.0 | passed |
| Single-node replicaset mongodb 4.4 | passed |
| Restore on new cluster mongodb 4.2 | passed |
| Single-node replicaset mongodb 4.0 | passed |

2022-01-20 10:33 UTC, merged