PBM-896: pass secure options to tmp mongod
percona/percona-backup-mongodb pull request #697
Opened 2022-08-31 16:37 UTC by dAdAbird

DO NOT MERGE

2022-08-31 19:54 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 5.0 | passed | passed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | passed | failed |
| Non-sharded psmdb 4.4 | passed | failed |
| Non-sharded psmdb 5.0 | passed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |

2022-09-02 21:33 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | passed | passed |
| Sharded psmdb 4.4 | passed | passed |
| Sharded psmdb 5.0 | failed | passed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.4 | failed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 5.0 | failed | failed |

2022-09-05 18:25 UTC, olexandr-havryliak commented on pbm/bsontypes.go
> +		KeyIdentifier         *string `bson:"keyIdentifier,omitempty" json:"keyIdentifier,omitempty" yaml:"keyIdentifier,omitempty"`
Please, also add **kmipClientCertificatePassword** 
https://github.com/percona/percona-server-mongodb/blob/v5.0/src/mongo/db/mongod_options_encryption.idl#L151-L158

2022-09-05 19:47 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Single-node psmdb 4.2 | passed | failed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.4 | passed | failed |
| Single-node psmdb 5.0 | passed | failed |

2022-09-06 11:38 UTC, dAdAbird commented on pbm/bsontypes.go
> +		KeyIdentifier         *string `bson:"keyIdentifier,omitempty" json:"keyIdentifier,omitempty" yaml:"keyIdentifier,omitempty"`
https://github.com/percona/percona-backup-mongodb/pull/697/commits/b08da272d7636b161a13f26bc36e281f78c8773e

2022-09-06 13:03 UTC, sandraromanchenko requested changes

2022-09-06 13:58 UTC, dAdAbird commented on pbm/bsontypes.go
> +		ServerName *string `bson:"serverName,omitempty" json:"serverName,omitempty" yaml:"serverName,omitempty"`
https://github.com/percona/percona-backup-mongodb/pull/697/commits/cbf813badcdb3ff83d52c2b863c28fb1aea2583d

2022-09-06 14:13 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | failed | failed |
| Sharded psmdb 5.0 | failed | failed |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Sharded psmdb 4.4 | - | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |
| Single-node psmdb 4.4 | passed | failed |
| Non-sharded psmdb 5.0 | failed | passed |

2022-09-06 17:10 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Single-node psmdb 5.0 | failed | passed |
| Sharded psmdb 4.2 | failed | passed |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | passed | failed |

2022-09-07 10:45 UTC, sandraromanchenko approved these changes

2022-09-07 10:47 UTC, merged