[PBM-948] align describe-backup and describe-restore output
percona/percona-backup-mongodb pull request #717
Opened 2022-09-22 12:36 UTC by defbin

2022-09-22 15:55 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.2 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| Non-sharded psmdb 4.2 | passed | passed |
| New cluster psmdb 5.0 | passed | - |
| Sharded psmdb 4.4 | failed | failed |
| Sharded psmdb 5.0 | passed | failed |
| Non-sharded psmdb 4.4 | passed | failed |
| Non-sharded psmdb 5.0 | passed | failed |
| Single-node psmdb 4.2 | failed | failed |
| Single-node psmdb 4.4 | failed | failed |
| Single-node psmdb 5.0 | failed | failed |

2022-09-23 09:44 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| Sharded psmdb 4.2 | passed | failed |
| New cluster psmdb 4.2 | passed | - |
| Sharded psmdb 4.4 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Non-sharded psmdb 4.2 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Sharded psmdb 5.0 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | passed | passed |

2022-09-27 12:26 UTC, dAdAbird requested changes

2022-09-27 12:26 UTC, dAdAbird commented on cli/restore.go
> +	LastWriteTime      string        `json:"last_write_time" yaml:"last_write_time"`
Restore doesn't have `LastWriteTime` (no need in L`astWriteTS` for that reason).

2022-09-27 14:47 UTC, dAdAbird approved these changes

2022-09-27 17:10 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.4 | failed | - |
| Sharded psmdb 4.2 | failed | failed |
| Non-sharded psmdb 4.2 | failed | failed |
| New cluster psmdb 5.0 | failed | - |
| New cluster psmdb 4.2 | failed | - |
| Sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.4 | passed | passed |
| Non-sharded psmdb 5.0 | failed | passed |
| Single-node psmdb 4.2 | failed | passed |
| Single-node psmdb 4.4 | failed | passed |
| Sharded psmdb 5.0 | failed | failed |
| Single-node psmdb 5.0 | passed | failed |

2022-09-27 17:14 UTC, merged