PBM-922 Updated the config file reference with SSE-C options
percona/percona-backup-mongodb pull request #732
Opened 2022-10-11 06:43 UTC by nastena1606

2022-12-08 11:01 UTC, defbin approved these changes

2022-12-29 16:39 UTC, sandraromanchenko requested changes

2022-12-29 16:39 UTC, sandraromanchenko commented on packaging/conf/pbm-conf-reference.yml
> +#       sseCustomerAlgorythm: AES256
correct name - sseCustomerAlgorithm

2023-01-10 12:41 UTC, sandraromanchenko approved these changes

2023-01-10 12:42 UTC, olexandr-havryliak approved these changes

2023-01-10 13:53 UTC, merged