PBM-1003 Fix ability to restore with remapping replicaset names
percona/percona-backup-mongodb pull request #751
Opened 2022-12-04 14:08 UTC by ziollek

When the logical backup is made by replicaset with a different name than the current one it is now posible to use that backup.

Changes include also refactor enabling the use of "e2e-ecosystem" for remapping tests. As a part of refactoring the following changes have been made:
- the ability to pass additional options to pbm restore command
- the ability to pass the name of the container with pbm agent
- new kind of tests (remapping) with dedicated docker-compose

Signed-off-by: ziollek <e.prace@gmail.com>

2022-12-10 18:13 UTC, deejay1 commented on e2e-tests/pkg/tests/sharded/test_remapping.go
> +				log.Fatalf("%s: cannot find apropriate mapping in: %v", name, re.Remapping)
s/apropriate/appropriate/

2022-12-13 08:32 UTC, defbin requested changes

2022-12-13 08:41 UTC, defbin commented on pbm/restore/logical.go
> +		_, bcpRS := path.Split(path.Dir(dump))
the file path is not a reliable source of the truth

2022-12-13 10:11 UTC, ziollek commented on pbm/restore/logical.go
> +				return stg.SourceReader(path.Join(bcp.Name, bcpRS, ns))
I've tested that reverse mapping have to be used in this case

2022-12-13 10:24 UTC, defbin approved these changes
LGTM

2022-12-13 10:26 UTC, defbin commented
@ziollek thank you for the contribution. very appreciated :+1:

2022-12-22 07:39 UTC, merged