Update README.md
percona/percona-backup-mongodb pull request #835
Opened 2023-05-18 16:21 UTC by nastena1606

Fixed some spelling and grammar errors

2023-06-05 10:07 UTC, defbin requested changes

2023-06-05 10:07 UTC, defbin commented on e2e-tests/README.md
> +To start tests with a running pbm-agent and minio storagee:
```suggestion
To start tests with a running pbm-agent and minio storage:
```

2023-06-05 10:09 UTC, defbin approved these changes

2023-06-06 15:34 UTC, merged

2023-06-06 17:31 UTC, JNKPercona commented
| Test name  | Logical | Physical |
| ------------- | ------------- | ------------- |
| New cluster psmdb 4.2 | passed | - |
| New cluster psmdb 5.0 | passed | - |
| Sharded psmdb 4.2 | passed | passed |
| Sharded psmdb 4.4 | failed | passed |
| New cluster psmdb 4.4 | passed | - |
| New cluster psmdb 6.0 | passed | - |
| Sharded psmdb 6.0 | failed | passed |
| Sharded psmdb 5.0 | failed | passed |
| Non-sharded psmdb 5.0 | passed | passed |
| Non-sharded psmdb 6.0 | passed | passed |
| Non-sharded psmdb 4.4 | failed | passed |
| Non-sharded psmdb 4.2 | passed | passed |
| Single-node psmdb 4.2 | passed | passed |
| Single-node psmdb 4.4 | passed | passed |
| Single-node psmdb 5.0 | passed | passed |
| Single-node psmdb 6.0 | passed | passed |